build:
  image: golang:1.7
  commands:
    - go get
    - go build
    - go test
compose:
  database:
    image: postgres
publish:
  docker:
    username: sammi
    password: $DOCKHUB_PASSWORD
    email: songyunhui2008@gmail.com
    repo: sammi/ci
